import type { AppConfig } from './types';

export const DEFAULT_CONFIG: AppConfig = {
  sites: [
    {
      id: 'ccgp',
      name: '中国政府采购网',
      baseUrl: 'http://www.ccgp.gov.cn',
      enabled: true,
      searchUrl:
        'http://search.ccgp.gov.cn/bxsearch?searchtype=1&page_index=1&bidSort=0&buyerName=&projectId=&pinMu=0&bidType=1&dbselect=bidx&kw=&start_time={startDate}&end_time={endDate}&timeType=6&displayZone=&zoneId=&pppStatus=0&agentName=',
      parserType: 'ccgp',
    },
    {
      id: 'yunnan_ggzy',
      name: '云南省公共资源交易中心',
      baseUrl: 'https://ggzy.yn.gov.cn',
      enabled: true,
      searchUrl:
        'https://ggzy.yn.gov.cn/home/inteligentsearch/searchResult?token=&searchData=%7B%22searchKey%22%3A%22%E9%93%81%E5%A1%94%22%2C%22searchType%22%3A%220%22%2C%22startTime%22%3A%22{startDate}%22%2C%22endTime%22%3A%22{endDate}%22%7D',
      parserType: 'yunnan_ggzy',
    },
    {
      id: 'cebpubservice',
      name: '中国招标投标公共服务平台',
      baseUrl: 'http://www.cebpubservice.com',
      enabled: true,
      searchUrl:
        'http://www.cebpubservice.com/ctpsp_iiss/searchbulletin/search?searchdata={keyword}&areacode=&timebegin={startDate}&timeend={endDate}',
      parserType: 'cebpubservice',
    },
    {
      id: 'chinabidding',
      name: '中国采购与招标网',
      baseUrl: 'https://www.chinabidding.com',
      enabled: true,
      searchUrl: 'https://www.chinabidding.com/search/searchzbgg?keywords={keyword}',
      parserType: 'chinabidding',
    },
  ],
  keywords: {
    include: [
      // 铁塔相关
      '铁塔',
      '钢管塔',
      '角钢塔',
      '格构式铁塔',
      '通信铁塔',
      '输电铁塔',
      '电力铁塔',
      '广播电视塔',
      '塔材',
      '塔架',
      '塔身',
      '塔基',
      '铁塔制造',
      '铁塔加工',
      '铁塔生产',
      '铁塔安装',
      '铁塔工程',
      '铁塔项目',
      '铁塔供货',
      // 云南地域
      '云南',
      '昆明',
      '大理',
      '丽江',
      '西双版纳',
      '曲靖',
      '玉溪',
      '保山',
      '昭通',
      '楚雄',
      '红河',
      '文山',
      '普洱',
      '临沧',
      '德宏',
      '怒江',
      '迪庆',
      '滇中',
      '滇西',
      '滇东',
      '滇南',
      '滇北',
      // 电力工程
      '输电线路',
      '输变电',
      '变电站',
      '换流站',
      '电力工程',
      '电网工程',
      '电力建设',
      '国家电网',
      '南方电网',
      '云南电网',
      '云南电力',
      '特高压',
      '超高压',
      '高压线路',
      '电力铁塔',
      '输电铁塔',
      '线路铁塔',
      // 通信基础设施
      '通信铁塔',
      '5G铁塔',
      '基站铁塔',
      '中国铁塔',
      '铁塔公司',
      '通信工程',
      '基站建设',
      '5G建设',
      // 钢结构
      '钢结构',
      '钢构件',
      '热镀锌',
      '防腐处理',
      '角钢',
      '钢管',
      '型钢',
    ],
    exclude: [
      '中标公告',
      '中标结果',
      '成交公告',
      '成交结果',
      '中标候选人公示',
      '中标候选人',
      '招聘',
      '求职',
      '人才',
      '岗位',
      '拍卖',
      '出让',
      '转让',
    ],
  },
  notification: {
    dingtalk: {
      enabled: false,
      webhookUrl: '',
      secret: '',
    },
  },
  schedule: {
    cron: '0 8,14,20 * * *',
    maxItemsPerRun: 50,
  },
};
